### ISSUE TITLE
Time before BC

### ISSUE THREAD

**Issue by lsyysl9711** [apoorvumang/CronKGQA#11]
Hello! 
Your work is great!

But in your train file, there is one line:

Q500099	P793	Q1190554	0600	0000

which means Jastorf culture occurred from 600 BC to 0(I searched it on google)

I do not think such labels are suitable, in my opinion it should be "-600" instead of "600" since we want to keep start_time < end_time.

But adding one minus symbol seems wired too, so do you have any other better solutions for this problem?

Thanks!

**Comment by lsyysl9711** [comment]
BTW: There are also some wired lines in train file as follows:

Q12717	P150	Q21802	1920	1871

which means from 1871 to 1920, Bas-Rhin had been a political location. I want to know why we should put 1920 in front of 1871? That is wired.

**Comment by apoorvumang** [comment]
Hi @lsyysl9711 , thanks for pointing the errors.

1. In the current state, BC is not supported, although as you correctly pointed out there do exist some facts which somehow did not get filtered out. We will be cleaning this up in case we release another version of the dataset but for now we are not removing these.

2. This is due to incorrect annotation in WikiData. You can check out the page here https://www.wikidata.org/wiki/Q12717. 
 
<p align="center">
  <img src="https://user-images.githubusercontent.com/1957903/145823809-495766e1-7f30-440a-9f53-b9b7f8b58c71.png" />
</p>
